name: registrar_client
description: A starting point for Dart libraries or applications.
version: "0.1.0"

environment:
  sdk: ^3.5.3

resolution: workspace


dependencies:
  signer:
    git:
      url: https://github.com/threefoldtech/tfgrid-sdk-dart
      ref: development
      path: packages/signer
  http: ^1.3.0
  bip39: ^1.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
