name: registrar_client
description: A starting point for Dart libraries or applications.
version: "0.1.0"

environment:
  sdk: ^3.5.3

resolution: workspace


dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
